name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: yarn predeploy
      - run: yarn deploy 
     
